tema3.o: tema3.c
	gcc tema3.c -c -o tema3.o -Wall

build: tema3.o
	gcc tema3.o -o tetripic -Wall

run_task1:
	./tetripic 1

run_task2:
	./tetripic 2

run_task3:
	./tetripic 3

run_task4:
	./tetripic 4

run_bonus:
	./tetripic bonus
	

clean:
	rm tetripic *.bmp ref* *.o
